### ISSUE TITLE
I meet an error when i install this module

### ISSUE THREAD

**Issue by LLYDB** [pruge/mybatis3#1]
When I run npm install mybatis3, (0.1.18)  an error occured.
I think it's because ""bin": {"cling": "./bin/cling.js"}" in package.json
Error is:
enoent ENOENT: no such file or directory, chmod '/Users/***/Documents/git/myproject/node_modules/mybatis3/bin/cling.js'

expect your response, 3Q!

**Comment by yanjunz** [comment]
I got the same issue. 
@LLYDB Have you solved it ?

**Comment by pruge** [comment]
Sorry for late reply
Fixed a bug
